

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://47.94.238.67:3306/seabow?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy # com.mysql.jdbc.Driver
