server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#spring:
#  datasource:
#    url: jdbc:p6spy:oracle:thin:@(DESCRIPTION =    (ADDRESS = (PROTOCOL = TCP)(HOST = 10.117.130.29)(PORT = 1521))    (CONNECT_DATA =      (SERVER = DEDICATED)      (SERVICE_NAME = ora29a)    ))
#    username: bmitest
#    password: bmitest
#    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
#mybatis:
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml

file:
  path: C:/tools/
spring:
  datasource:
    url: jdbc:mysql://10.117.150.34:33306/seabow
    username: root
    password: 2018@Com.
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#  spring.data.mongodb.uri=mongodb://name:pass@localhost:27017/test
  data:
    mongodb:
      uri: mongodb://10.117.150.41:27017/bmitest
